// Modobeam — "How I'm starting to know you" note.
// Refreshes every ~10 reflections. Stored locally, generated by the
// know-you edge function. Visible on Preferences.

const KEY = "modobeam_know_you_v1";

export interface KnowYouNote {
  text: string;
  generatedAtCount: number; // total reflections at time of generation
  generatedAt: string;
}

export function readKnowYou(): KnowYouNote | null {
  try {
    const raw = localStorage.getItem(KEY);
    if (!raw) return null;
    return JSON.parse(raw) as KnowYouNote;
  } catch {
    return null;
  }
}

export function writeKnowYou(note: KnowYouNote): void {
  localStorage.setItem(KEY, JSON.stringify(note));
}

export function shouldRegenerate(totalReflections: number): boolean {
  if (totalReflections < 10) return false;
  const existing = readKnowYou();
  if (!existing) return true;
  return totalReflections - existing.generatedAtCount >= 10;
}
