export const layout = {
  shellInner: "mx-auto w-full max-w-md px-5",
  pageSection: "animate-fade-up",
  pageSectionGap: "space-y-10",
  pageIntro: "space-y-4",
  pageHeader: "pt-3 pb-7",
  eyebrow: "text-[10px] font-medium uppercase tracking-[0.28em] text-muted-foreground/90",
  title: "font-display text-[2.05rem] leading-[1.02] font-medium text-foreground",
  titleSm: "font-display text-[1.78rem] leading-[1.08] font-medium text-foreground",
  body: "text-[13px] leading-[1.7] text-muted-foreground",
  surface: "rounded-[1.9rem] border border-border/60 bg-card/82 backdrop-blur-xl shadow-soft",
  surfaceSoft: "rounded-[1.7rem] border border-border/55 bg-card/74 backdrop-blur-xl shadow-soft",
  chipRow: "flex flex-wrap gap-2",
  helperRow: "mt-3 flex flex-wrap items-center justify-between gap-x-3 gap-y-2",
  splitHeader: "flex items-baseline justify-between gap-3",
  sectionStack: "space-y-5",
  cardStack: "space-y-3.5",
  actionBlock: "mt-8",
  sectionLabel: "text-[10px] font-medium uppercase tracking-[0.28em] text-muted-foreground/88",
  sectionHint: "text-[12.5px] leading-[1.65] text-muted-foreground/82",
} as const;
