export const layout = {
  shellInner: "mx-auto w-full max-w-md px-5",
  pageSection: "animate-fade-up",
  pageSectionGap: "space-y-10",
  pageIntro: "space-y-4",
  pageHeader: "pt-3 pb-7",
  eyebrow: "text-[10px] font-semibold uppercase tracking-[0.28em] text-foreground/58",
  title: "font-display text-[2.34rem] leading-[0.96] font-semibold text-foreground",
  titleSm: "font-display text-[1.84rem] leading-[1.02] font-semibold text-foreground",
  body: "text-[13.5px] leading-[1.68] text-muted-foreground/96",
  surface: "rounded-[1.35rem] border border-border/80 bg-card/96 shadow-soft",
  surfaceSoft: "rounded-[1.1rem] border border-border/72 bg-card/92 shadow-soft",
  chipRow: "flex flex-wrap gap-2",
  helperRow: "mt-3 flex flex-wrap items-center justify-between gap-x-3 gap-y-2",
  splitHeader: "flex items-baseline justify-between gap-3",
  sectionStack: "space-y-4.5",
  cardStack: "space-y-3.5",
  actionBlock: "mt-8",
  sectionLabel: "text-[10px] font-semibold uppercase tracking-[0.26em] text-foreground/60",
  sectionHint: "text-[12.5px] leading-[1.62] text-muted-foreground/94",
} as const;
