export const layout = {
  shellInner: "mx-auto w-full max-w-md px-5",
  pageSection: "animate-fade-up",
  pageSectionGap: "space-y-10",
  pageIntro: "space-y-4",
  pageHeader: "pt-3 pb-7",
  eyebrow: "text-[10px] font-semibold uppercase tracking-[0.28em] text-foreground/54",
  title: "font-display text-[2.18rem] leading-[0.98] font-semibold text-foreground",
  titleSm: "font-display text-[1.78rem] leading-[1.08] font-medium text-foreground",
  body: "text-[13px] leading-[1.68] text-muted-foreground/92",
  surface: "rounded-[1.5rem] border border-border/75 bg-card/94 shadow-soft",
  surfaceSoft: "rounded-[1.25rem] border border-border/70 bg-card/88 shadow-soft",
  chipRow: "flex flex-wrap gap-2",
  helperRow: "mt-3 flex flex-wrap items-center justify-between gap-x-3 gap-y-2",
  splitHeader: "flex items-baseline justify-between gap-3",
  sectionStack: "space-y-4.5",
  cardStack: "space-y-3.5",
  actionBlock: "mt-8",
  sectionLabel: "text-[10px] font-semibold uppercase tracking-[0.26em] text-foreground/56",
  sectionHint: "text-[12.5px] leading-[1.6] text-muted-foreground/88",
} as const;
